### ISSUE TITLE
Issue with Helm2 tillerless on Rancher

### ISSUE THREAD

**Issue by ananace** [hickeyma/helm-mapkubeapis#31] opened 2020-06-24 07:33 UTC
Support for Rancher installed applications would be great, as it seems they're doing something different to regular tillerless for their Helm 2 installs.

An example Rancher release from one of our clusters - not one that needs to be patched but rather one that displays the issue without including any secrets;
```sh
$ kubectl --namespace=aleol57 get cm kube-ops-view.v3 -o yaml
apiVersion: v1
data:
  release: H4sIAAAAAAAC/+xbzY8kyVXXfO2MAyMtjYXECovnalvabU9mfUxPd09KIzE7MzaNvbOt6Zmx0Gq1E5X5qiqmIzPSEZHVU+4tJISEfEDygauBA0j8EUgc7AsHOHC0kJE4wAGEuGCBJRAoIjIrP+pjqnpm7ZV36tCqiox48T5+78WLl6/JL59kffREqrwxw9Otn14if3Pp2oXWDy89EkDDEJUCPUL4RtZHmaBGBe+nKKlmIqEcnjA8hceHASFdH77GpNKgNJXarjGUQ80hleL5JCAEoD5ESM+HB+IURIqJXTEQnItTlgzh8cNvAktgIjIJfSlOFUpHYaR1GrTbXISUj4TSwUGn023TlLXH3bYl205ojCqlIao25Sj4zf22QjlmZqAmbZuQr0kRg8i0YhFaFkKeKY3yuv1hlqF0zCi7f759QcE/menFZ9rnLPMVtgk54kgVgpYTkMgFjYxMhmJKhwhsYAQDhQitY8fZ44SOKeO0zxHakAjAJEoFS7SC8sFASMglaV2HVEQQSrSmgJgNRxo0PUGgEIsYE+2Trc9f+6O//4d/vvLmv//3j/7w0lufv/ajv/7Bf1158/v/8cffu7Dz5uN0KGmEEIo45ajxrb/9FvnXi01AvG0kVkG7PWR6lPX9UMTt0TMain5DmW+tPbN1pev3/M7Ow1Wg8kAijTyR8AmoidIYQ0TVqC+ojKwi4oxrlnKEbxyowmqqR0qD9D43W9AjoqCvgi+SqzlbW1sjTBKWDH/L/e76Eb57ZSh0yn/ncSGNpKe+kyhTKEORaKPbpcK1Y2o4qQ96XAyFnybDhxfH3Wdv9Dr+rt/Z+sll8qsa45RTjar94P1H9499/Vxv/fjyL4TvnZ2B/xCtI/gPimGYTktnPDuDQn5o1RTmDzLODa0W+GYJIWdnxm38J5RnxteSoUSlfEyMY0TgTafncuXFVDVXMJ2qszPjhTCdBm0rTGOW0YBhEabTBU9TqkcwnVrGDRXD4ackKvzgGvm1EncfjZCnKJWvU771l9fOzto7MGZxAAo1DBhHPUnxdpwpTcMRBrDTnk6JmUXuP09pElkBrB7EwKl9RKX2ST7PgwgHLJkzsDOuV86hGdfg37WLDVxmGjUz3x+jlMauH4OWWRLC3g37lcXH2WDAnkPLK4kV6nZc3jXKMPIXexhoTeDbGeVswDACmqaWf598Cx11O1+bPYwsCvoY0kwhKBHXvNFKPWDIIwVUInAWM40RaAF6xBS83Z9Yjdx7cGzmGmurFMN3fHI4MAiwaLBETFihLFFOeW6MaThlnEMfIVOGTwXUMp9z+wIFlx5U6KWC9OLhTK/FnKUT1lI8VyWlL1shgtvr27bC50wfjkotjpS81kY3ZjCVLNEDaH1FeV9RrQY1t+8maFv2vYbCinmN64xRKuOnVDkT53hxszjtI3+hme3c1lKhqjp335/ke34MElNuQnLrqy1ofdTaSNqtH14hb5VBJA+1UnD0JzTmW39xpYE42aehHzotGAI0ZTknAdhnNNMjIdl3bOTyTw6Uz0R73O2jpl1ywpIogLtul4eCI4lR04hqGhBwmlLmGxhvriVlwh5JAZhIn4Q8i5ZEInPMWAIj5LGvRm2r2FXrcs3PFs7vHNOEDjHy+hNLZ4awPLovX8gSpWkSYn3ZA3fYLFkzLrRpljhT30nTwtpLl6VUak8Mlu00U956BzWRGUcVEA9oyr4uRZaqAD5otT4kABKVyGSIdiQREarWdWilIlL28Rhl3z7iTOnWh00SMWrJQpUDYyOCQ9TmQU63huI/f4N8aSGK+ywxp7MD8/9+wmB+1232GtOfUkwLjg9xYGxRQHKFmQnAfLTafFOV9Z9hqC0CvJxiruM7YSiyRFvhNyVbrLHJ+LyCihy97iV/9QXy66WXRJhyMbG5pPWOP/lCFf40TVV7XID83mxuDdxrwtfy+9oRPiFHMKloYMNoyllIlZtVRDg3eNcAzdFXyDHUQjpLxFSHo29WTPMKjHMOVy5QmTNVgZj58Bp/r4TDl4DQS8HovFB6CTidyyDu0zguUxE5qLjIAlr8Lo35gscfA0siTDQcNKm5i7gdKnC7YCM6GLCE6UkFUflIsGDf2exF2zY2ndvK5BvHuUuUk6qji7asrTrPtlrwopBVzqkMLtq0umbtPU+ZHlUtdIxhJpme3BWJxue6nKzqD2oMrLedqh1rD2YuuTjfstWW9U67szN345tOW9XQZojN75nPqnGWX0NRzoKIV55d1btVBa0spkMMoLqjHTIhVSimhTTwDOYeazo0LNTpHGWcHwnOwkktOrsV6ezhCt+TGLGyTlZ1bTmshEYPPM9O9TLJb9tvedWr4eP5LFflDGonhtnIjfupkHqFCy8EmVqGsHmMQR1jSQ6ybucFexq2akLPDHwk8mBecmMB4rNEo0woP2pIxNkYE1TqSIo+liRdWfHrqKtDACnVowDaI6Rcj+pPNt1YIo3Yz2nn4r61IMjMHpY+3+2Z1Vs/vVotNxb1UZs6/uPVBloX1XWr2SU+15iYr6pxmzp0CxdnmWvnxq9zzU8o11xiZpokQldPs8rAIpAtWjeD22713lLNb11Jwjm8fW0Bq6v5pHSn0peMH6mqa3m5a62o/Ve9rU/DE0yiunPOzr4H57jGzRFZGsOM11Qdeok13GsPk1XzldrXfJnW56qE36v5fsGP9f3/fKPq2LMbYw7pl3LkhnzFtpuibdG6pWh7HTx+VsGjMAtfcaVozHlhjNCTFBe6jnng2J7lDt7yk7PpaDY5p3KIeqP8IpVCi1DwAB7dPZq7er8Utra+e5l8cc4jqUuDnWP+y6UNqp1Nvy1qU69LmZ/KUmY1OLf+7zL5n8uzCzKcTYm7uxiwV+4dh4MHQh9JVGhrjuU1JoCFHRDGnegwANflQPJTI2jEW7MdQJ7nBTCgXCEBKI7hAOpy2J4DMktn80MKPviQ1K7chuqsnFD8Op67PUyJwbRhycG63H/RXTR/gUncrcgscpVdh+g5EeYG8ruSc21jcKXRoCc/xefmZwqPqFKnQs4Gq+W4ALqkkoqDe+2c+1eYZgF0O504L4jF1k7d3sF7zNru2xmq2tyDxtS93fcYUQs0lmvGLK2GOUOBAFTDmBmygy6q5nXwwyNSrVMY0+38+CL5Jd94NBsmQuLW313chiOqDSkFWoAbhtMRJtDPGLcNEykNT+gQlU+24dGIKVBZaoMzqBFyDkMu+q4+yZLhdZDIqWZjtNCpjNMkItuQ4NC1SrydShyw5xi5S+mX3vHh/YRPQCR2pWHJGA84S9An/r3jj461kEi24a6IY5HAk7vHEDGpiD9kum3/OvaJ3/+ObNu/xcBo2DZ/ip9qnLRLQiZTzFLbeqHIjq9OU7Lj9+kJ2fF1nJKd3yPb8IRKJjIFh/fuK+KnUjzDUBOfRUjbbp4Uz8jOH1wjn3t4/8699+77cbT1k6vbK3uJfht5DDY0EfLBiokfrt3p9Y45ysYsQgX0XP1chGxvw6EJt5wXzTI5h48EMPeg8s7c2s78rHVXxBMv/x0Q8vTp01AkSnAkX7anyYyM55nZt8vZoLRxzUZ4e/r0KSGPRrZxLqZJBO6FiFqpW5E0W7lyEYG5J0WXRCiSARtmbrVv5b9jW8EK8R8fNmSo93VZ7ra34bFdYPXx0MSt1YIr1FCrFN3WMsONNHJHqcy2uExE5roZnpbrnloT5/tZ0a7beSFNIBGn1W63x4fN5jPoT2ybmiG+WQtartSy46zkyGt2ghqdJWwZ1LLiUTtCjto1mFX0Ur4UWwixfFG5YB5FEmMxNo6SA7oKFRGnIkHb9qWUCBnVRZwqoe+QyO2Cigf4ZOeI/EbI2q5ul5vXG7vUziZ8ndnBNjuKjPWbJ5eN7Hs39m+Rnd+/SH7FnCVMohFZmeP5ZOvfLkSYokm0Q+aaANxJbsk3M4c8gpTZjmfFUL7SQtIh+kMhhhxpypSJL+59vsuguh3/ht8hERuiucyrEe3d3Av6nU6/F+3v4q3OAe0d0MHgAAf7+53Bjd5uuB/uRrf60W53d3ATKb1Jb/b3BhTD/b1btwY3DvZpf48MMTFOa8Rv9TrdW163593oPOruBb2bQXff392/2bmx99VON+h0WmTnTy80dGB1+d0X6KAuxM7LayUUScS06zyoOjBp/dkF8v0L5jCkvJK0uJRmlk65k8MNpp7iu6f9asbWBESZnq3sgJ5Lr+zyehLTIzv/9JvE8zyyDcc2mWnkfO2V15RP5BbSzGPnrhv1rl7bxrzG5eIR4xzlCy8T87uvuEbk2fULbg1NkovEXM8EzQ6vn3kD12fSNp/+dqqN0VPtrPp5NU59NrH06tqY6oQ3alWaF77SjpT/u85mp8KLj4MFxeQmG69R06iFlrf2BaXPg85caTO/8p+3eHmeI6nRiEbO2Yb2GgpLoVC2hvVepgNsnt+NgtmrafJaxMTaZtvIdJubb30Tbqi6erfUouLmImaWt70sZr1oeVlYAwoc9ysaWxoF5vVaNWbx5tU3Y9RIv+J2iwbtShW3/FTrueWnXtktP80ab/mpV3sblA6WErIV4PUicLWZ42X7NF6H4eVheL6DYfX1e6MGhvbGfQqLo8CCXoSDzsGld6/mWd3/BwAA//9H/OsIaz4AAA==
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-22T12:09:03Z"
  labels:
    MODIFIED_AT: "1592827743"
    NAME: kube-ops-view
    OWNER: TILLER
    STATUS: DEPLOYED
    VERSION: "3"
  name: kube-ops-view.v3
  namespace: aleol57
  resourceVersion: "555991060"
  selfLink: /api/v1/namespaces/aleol57/configmaps/kube-ops-view.v3
  uid: ba7497cf-5a60-48eb-9d56-0f6c0c176a8a
$ helm mapkubeapis --v2 --tiller-out-cluster --release-storage configmaps --namespace aleol57 kube-ops-view
2020/06/24 09:26:43 Release 'kube-ops-view' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/06/24 09:26:43 Get release 'kube-ops-view' latest version.
Error: Failed to get release 'kube-ops-view' latest version: release: "kube-ops-view" not found
Error: plugin "mapkubeapis" exited with error
$ helm plugin list | grep mapkubeapis                                                        
mapkubeapis     0.0.14  Map release deprecated Kubernetes APIs in-place
```

**Comment by hickeyma** [comment] 2020-06-24 07:44
@ananace Thanks for raising the issue.

I have a few questions about this. Does rancher use Tillerless for Helm v2? What is the output of `helm history kube-ops-view`?

**Comment by ananace** [comment] 2020-06-24 08:01
Rancher uses a patched helm/tiller instead of tillerless, though the actual process for doing application changes is much the same. (spin up in-application tiller, perform actions, spin down in-application tiller)

If I drop in the same (official) helm version as rancher - along with the tillerless plugin - that seems to work fine though.
```
$ HELM_TILLER_STORAGE=configmap helm tiller run aleol57 -- helm history kube-ops-view
Installed Helm version v2.16.8
Installed Tiller version v2.16.8
Helm and Tiller are the same version!
Starting Tiller...
Tiller namespace: aleol57
Running: helm history kube-ops-view

REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION     
1               Wed Apr 17 10:49:16 2019        SUPERSEDED      kube-ops-view-0.7.0     0.9             Install complete
2               Mon Jun 22 14:08:46 2020        SUPERSEDED      kube-ops-view-1.2.0     20.4.0          Upgrade complete
3               Mon Jun 22 14:08:57 2020        DEPLOYED        kube-ops-view-1.2.0     20.4.0          Upgrade complete
Stopping Tiller...
```

**Comment by hickeyma** [comment] 2020-06-24 08:35
The plugin uses the Helm v2 SDK to get the last deployed version for a release. It is therefore using the standard Helm APIs.

What does it mean when you say that "Rancher uses a patched helm/tiller instead of tillerless"? Have they forked the Helm repo and made changes in it? Even though a Configmap is been created and looks the same , there maybe some differences in the release object stored in data.

Do you mind raising this with rancher to see if there are any differences which might be a factor?

**Comment by ananace** [comment] 2020-06-24 08:52
Rancher does have their [own helm/tiller fork](https://github.com/rancher/helm) that does the same thing as tillerless for them, though it seems to relegate fewer things still to the tiller instance - instead using the Rancher application itself to do read operations.

Though it seems like the whole Rancher part has been a red herring, rather it just seems like the Helm V2 mode doesn't work when run through Helm 3. When I ran the same command with the Helm 2.16.8 version I'd pulled - while testing for differences with a regular tiller install - then everything actually went just fine;

```sh
$ helm mapkubeapis --v2 --namespace=aleol57 --tiller-out-cluster --release-storage configmaps kube-ops-view
2020/06/24 10:43:28 Release 'kube-ops-view' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/06/24 10:43:28 Get release 'kube-ops-view' latest version.
2020/06/24 10:43:28 Check release 'kube-ops-view' for deprecated or removed APIs...
2020/06/24 10:43:28 Found deprecated or removed Kubernetes API:
"apiVersion: extensions/v1beta1
kind: Ingress"
Supported API equivalent:
"apiVersion: networking.k8s.io/v1beta1
kind: Ingress"
2020/06/24 10:43:28 Found deprecated or removed Kubernetes API:
"apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding"
Supported API equivalent:
"apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding"
2020/06/24 10:43:28 The following API does not require mapping as the API is not deprecated or removed in Kubernetes 'v1.17':
"apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding"
2020/06/24 10:43:28 Finished checking release 'kube-ops-view' for deprecated or removed APIs.
2020/06/24 10:43:28 Deprecated or removed APIs exist, updating release: kube-ops-view.
2020/06/24 10:43:28 Set status of release version 'kube-ops-view.v3' to 'superseded'.
2020/06/24 10:43:28 Release version 'kube-ops-view.v3' updated successfully.
2020/06/24 10:43:28 Add release version 'kube-ops-view.v4' with updated supported APIs.
2020/06/24 10:43:28 Release version 'kube-ops-view.v4' added successfully.
2020/06/24 10:43:28 Release 'kube-ops-view' with deprecated or removed APIs updated successfully to new version.
2020/06/24 10:43:28 Map of release 'kube-ops-view' deprecated or removed APIs to supported versions, completed successfully.
$ helm version
Client: &version.Version{SemVer:"v2.16.8", GitCommit:"145206680c1d5c28e3fcf30d6f596f0ba84fcb47", GitTreeState:"clean"}
Error: could not find tiller

$ PATH=/usr/bin helm mapkubeapis --v2 --namespace=aleol57 --tiller-out-cluster --release-storage configmaps kube-ops-view
2020/06/24 10:49:55 Release 'kube-ops-view' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/06/24 10:49:55 Get release 'kube-ops-view' latest version.
Error: Failed to get release 'kube-ops-view' latest version: release: "kube-ops-view" not found
Error: plugin "mapkubeapis" exited with error
$ PATH=/usr/bin helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800e", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by hickeyma** [comment] 2020-07-30 10:25
@ananace  I tested it using 2 different kind clusters as follows:

```console
$ kubectl config get-contexts
CURRENT   NAME           CLUSTER        AUTHINFO       NAMESPACE
*         kind-kind-17   kind-kind-17   kind-kind-17   
          kind-kind-18   kind-kind-18   kind-kind-18   

$ kubectl config current-context
kind-kind-17

$ helm3 ls --kube-context kind-kind-18
NAME        	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            	APP VERSION
fail-deploy 	default  	1       	2020-07-07 11:28:01.515686017 +0000 UTC	failed  	fail-deploy-0.1.0	1.16.0     
issue-8397  	default  	4       	2020-07-07 11:32:00.416289781 +0000 UTC	deployed	issue-8397-0.1.0 	1.16.0     
mychart     	default  	52      	2020-07-16 10:59:27.890313424 +0000 UTC	deployed	mychart-0.1.0    	1.16.0     
mychart-test	default  	1       	2020-07-15 08:21:56.539403207 +0000 UTC	deployed	mychart-0.1.0    	1.16.0     

$ helm3 mapkubeapis mychart --dry-run
2020/07/30 10:15:52 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 10:15:52 Run without --dry-run to take the actions described below:
2020/07/30 10:15:52 
2020/07/30 10:15:52 Release 'mychart' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 10:15:52 Get release 'mychart' latest version.
Error: failed to get release 'mychart' latest version: release: not found
Error: plugin "mapkubeapis" exited with error

$ helm3 mapkubeapis mychart --dry-run --kube-context kind-kind-18
2020/07/30 10:16:03 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 10:16:03 Run without --dry-run to take the actions described below:
2020/07/30 10:16:03 
2020/07/30 10:16:03 Release 'mychart' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 10:16:03 Get release 'mychart' latest version.
2020/07/30 10:16:03 Check release 'mychart' for deprecated or removed APIs...
2020/07/30 10:16:03 Finished checking release 'mychart' for deprecated or removed APIs.
2020/07/30 10:16:03 Release 'mychart' has no deprecated or removed APIs.
2020/07/30 10:16:03 Map of release 'mychart' deprecated or removed APIs to supported versions, completed successfully.
```

From my testing, the kubecontext seems to be working as expected.

**Comment by ananace** [comment] 2020-07-30 12:42
I've only been able to reproduce the kube-context issue on helm 2, which I also seem to need to use in order to handle Rancher / Helm 2 resources.

**Comment by hickeyma** [comment] 2020-07-30 13:30
Ok sorry, missed running it for v2 resources. I tested it with v2 resources and it works as follows:

```console
$ helm2 ls
NAME            	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
mychart-v2-k8s17	1       	Thu Jul 30 09:38:45 2020	DEPLOYED	mychart-0.1.0	1.0        	default  

$ helm2 ls --kube-context kind-kind-18
NAME      	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
mychart-v2	1       	Thu Jul 30 09:20:49 2020	DEPLOYED	mychart-0.1.0	1.0        	default 

$ helm3 mapkubeapis mychart-v2 --v2 --dry-run
2020/07/30 13:26:24 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 13:26:24 Run without --dry-run to take the actions described below:
2020/07/30 13:26:24 
2020/07/30 13:26:24 Release 'mychart-v2' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 13:26:24 Get release 'mychart-v2' latest version.
Error: Failed to get release 'mychart-v2' latest version: release: "mychart-v2" not found
Error: plugin "mapkubeapis" exited with error

$ helm3 mapkubeapis mychart-v2 --v2 --dry-run --kube-context kind-kind-18
2020/07/30 13:26:11 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 13:26:11 Run without --dry-run to take the actions described below:
2020/07/30 13:26:11 
2020/07/30 13:26:11 Release 'mychart-v2' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 13:26:11 Get release 'mychart-v2' latest version.
2020/07/30 13:26:11 Check release 'mychart-v2' for deprecated or removed APIs...
2020/07/30 13:26:11 Finished checking release 'mychart-v2' for deprecated or removed APIs.
2020/07/30 13:26:11 Release 'mychart-v2' has no deprecated or removed APIs.
2020/07/30 13:26:11 Map of release 'mychart-v2' deprecated or removed APIs to supported versions, completed successfully.
```

Don't seem to be able to reproduce unfortunately. Would you be able to troubleshoot it and provide me with some details that I could try and debug?

**Comment by ananace** [comment] 2020-07-30 13:59
Dropped in separate helm 2 and 3 binaries to better show off what's going on for me; Using the helm-tiller plugin to show the tillerless helm2 data that Rancher uses.
The things that I could see as differing are; Tillerless, and configuration storage in configmaps instead of secrets. Either of the two - or the combination of both - might be what's causing the issues.

```shellsession
$ kubectl config use-context b
Switched to context "b".

$ HELM_TILLER_STORAGE=configmap helm2 tiller run ctrlc-ace -- helm2 ls
Installed Helm version v2.16.8
Installed Tiller version v2.16.8
Helm and Tiller are the same version!
Starting Tiller...
Tiller namespace: ctrlc-ace
Running: helm2 ls

NAME            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
gitlab-runner   10              Wed Jun 24 16:00:14 2020        DEPLOYED        gitlab-runner-0.18.0-rc1        13.1.0-rc1      ctrlc-ace
mc-eternal      14              Wed Jun 24 16:00:29 2020        DEPLOYED        minecraft-1.2.0                 1.14.4          ctrlc-ace
Stopping Tiller...

$ kubectl config use-context a
Switched to context "a".

$ helm2 mapkubeapis gitlab-runner --kube-context b --v2 --dry-run --release-storage configmaps --tiller-out-cluster --namespace=ctrlc-ace
2020/07/30 15:54:50 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 15:54:50 Run without --dry-run to take the actions described below:
2020/07/30 15:54:50 
2020/07/30 15:54:50 Release 'gitlab-runner' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 15:54:50 Get release 'gitlab-runner' latest version.
Error: Failed to get release 'gitlab-runner' latest version: release: "gitlab-runner" not found
Error: plugin "mapkubeapis" exited with error

$ helm3 mapkubeapis gitlab-runner --kube-context b  --v2 --dry-run --release-storage configmaps --tiller-out-cluster --namespace=ctrlc-ace
2020/07/30 15:54:54 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 15:54:54 Run without --dry-run to take the actions described below:
2020/07/30 15:54:54 
2020/07/30 15:54:54 Release 'gitlab-runner' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 15:54:54 Get release 'gitlab-runner' latest version.
Error: Failed to get release 'gitlab-runner' latest version: release: "gitlab-runner" not found
Error: plugin "mapkubeapis" exited with error

$ kubectl config use-context b
Switched to context "b".

$ helm2 mapkubeapis gitlab-runner --kube-context b --v2 --dry-run --release-storage configmaps --tiller-out-cluster --namespace=ctrlc-ace
2020/07/30 15:55:29 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 15:55:29 Run without --dry-run to take the actions described below:
2020/07/30 15:55:29 
2020/07/30 15:55:29 Release 'gitlab-runner' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 15:55:29 Get release 'gitlab-runner' latest version.
2020/07/30 15:55:29 Check release 'gitlab-runner' for deprecated or removed APIs...
2020/07/30 15:55:29 Finished checking release 'gitlab-runner' for deprecated or removed APIs.
2020/07/30 15:55:29 Release 'gitlab-runner' has no deprecated or removed APIs.
2020/07/30 15:55:29 Map of release 'gitlab-runner' deprecated or removed APIs to supported versions, completed successfully.

$ helm3 mapkubeapis gitlab-runner --kube-context b --v2 --dry-run --release-storage configmaps --tiller-out-cluster --namespace=ctrlc-ace
2020/07/30 15:55:40 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/07/30 15:55:40 Run without --dry-run to take the actions described below:
2020/07/30 15:55:40 
2020/07/30 15:55:40 Release 'gitlab-runner' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2020/07/30 15:55:40 Get release 'gitlab-runner' latest version.
Error: Failed to get release 'gitlab-runner' latest version: release: "gitlab-runner" not found
Error: plugin "mapkubeapis" exited with error

$ helm2 version
Client: &version.Version{SemVer:"v2.16.8", GitCommit:"145206680c1d5c28e3fcf30d6f596f0ba84fcb47", GitTreeState:"clean"}
Error: could not find tiller

$ helm3 version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800e", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by rimusz** [comment] 2020-07-30 14:34
@ananace I never used Rancher, but on GKE I used helm v2 with Tillerless plugin a lot, and recently I did convert with `helm-mapkubeapis` many releases without issues which were installed with tillerles plugin, but of course releases were stored in secret.

**Comment by hickeyma** [comment] 2020-08-25 08:33
@ananace I am still unsure that this is an issue with using the community version of Helm. Looking through the discussion thread so far, it would seem to be more related to the rancher environment.

Have you had a chance to investigate this further with rancher?

**Comment by hickeyma** [comment] 2020-08-25 08:36
I am also going to change the title as this issue should not be about adding support for the rancher version of Helm. The Helm version on rancher should be compatible with the community version of Helm.

**Comment by hickeyma** [comment] 2020-10-06 17:08
@ananace Any update on this?

**Comment by ananace** [comment] 2020-10-08 06:54
I'm still seeing the exact same issues, now with Helm 3.3.4. If I want to act on Rancher-installed Helm 2 releases - tillerless, releases in configmaps - then I have to use a Helm 2 version locally, and I also need to switch to the correct context globally beforehand.

I'll have a look at the releases I have installed, see if I can extract one of them into another cluster, verify that it's not something there that's bugging. If I have one without any sensitive information I can pass it over here too.

**Comment by hickeyma** [comment] 2020-10-08 10:05
I understand @ananace that you might not be able to show your data but without more information I am unfortunately able to troubleshoot this further to identify the issue. if you can show how to reproduce this then that would be great.

**Comment by hickeyma** [comment] 2020-11-16 11:48
Ping @ananace

**Comment by hickeyma** [comment] 2020-12-16 12:11
Any further feedback on this @ananace

**Comment by hickeyma** [comment] 2021-03-02 09:59
Closing as no further details on this issue. We can re-open if need be.

**Closed by hickeyma** 2021-03-02 09:59 UTC
Labels: question
