### ISSUE TITLE
mapkubeapis plugin not finding release

### ISSUE THREAD

**Issue by ramalhais-sky** [hickeyma/helm-mapkubeapis#47] opened 2021-05-12 12:56 UTC
Hi!
mapkubeapis plugin is not finding release "gitlab"

# Helm version
```
helm2 version
...
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

# mapkubeapis version
```
$ helm2 plugin list | grep mapkubeapis        
...
mapkubeapis     0.0.15  Map release deprecated Kubernetes APIs in-place
```

# List releases in namespace imp-gitlab
```
$ helm2 --kube-context=imp-hhe-prd --namespace imp-gitlab list
...
NAME    REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE 
gitlab  13              Thu May 21 13:44:06 2020        DEPLOYED        gitlab-2.0.3    master          imp-gitlab
```

# List secrets in namespace kube-system
```
$ kubectl --context imp-hhe-prd -n kube-system get secret|grep gitlab
gitlab.v10                                           Opaque                                1      553d
gitlab.v11                                           Opaque                                1      518d
gitlab.v12                                           Opaque                                1      356d
gitlab.v13                                           Opaque                                1      356d
gitlab.v4                                            Opaque                                1      673d
gitlab.v5                                            Opaque                                1      673d
gitlab.v6                                            Opaque                                1      673d
gitlab.v7                                            Opaque                                1      587d
gitlab.v8                                            Opaque                                1      574d
gitlab.v9                                            Opaque                                1      553d
```

# Running mapkubeapis
```
$ helm2  mapkubeapis --kube-context imp-hhe-prd --namespace kube-system --v2 gitlab
...
2021/05/12 13:52:53 Release 'gitlab' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2021/05/12 13:52:53 Get release 'gitlab' latest version.
Error: Failed to get release 'gitlab' latest version: release: "gitlab" not found
Error: plugin "mapkubeapis" exited with error
```

Any idea of what is going on?
How can i debug this issue?

Thank you!

**Comment by ramalhais-sky** [comment] 2021-05-12 14:03
I found the problem. mapkubeapis is ignoring flag --kube-context imp-hhe-prd
Had to change the current cluster with kubectx imp-hhe-prd:

```
$ kubectx imp-hhe-prd
Switched to context "imp-hhe-prd".

$ helm2  mapkubeapis --kube-context imp-hhe-prd --namespace kube-system --v2 gitlab --debug 
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable"
2021/05/12 14:58:59 Release 'gitlab' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2021/05/12 14:58:59 Get release 'gitlab' latest version.
2021/05/12 14:59:03 Check release 'gitlab' for deprecated or removed APIs...
2021/05/12 14:59:03 Found deprecated or removed Kubernetes API:
"apiVersion: apps/v1beta2
kind: Deployment"
Supported API equivalent:
"apiVersion: apps/v1
kind: Deployment"
2021/05/12 14:59:03 Found deprecated or removed Kubernetes API:
"apiVersion: apps/v1beta2
kind: StatefulSet"
Supported API equivalent:
"apiVersion: apps/v1
kind: StatefulSet"
2021/05/12 14:59:03 Finished checking release 'gitlab' for deprecated or removed APIs.
2021/05/12 14:59:03 Deprecated or removed APIs exist, updating release: gitlab.
2021/05/12 14:59:03 Set status of release version 'gitlab.v13' to 'superseded'.
2021/05/12 14:59:03 Release version 'gitlab.v13' updated successfully.
2021/05/12 14:59:03 Add release version 'gitlab.v14' with updated supported APIs.
2021/05/12 14:59:04 Release version 'gitlab.v14' added successfully.
2021/05/12 14:59:04 Release 'gitlab' with deprecated or removed APIs updated successfully to new version.
2021/05/12 14:59:04 Map of release 'gitlab' deprecated or removed APIs to supported versions, completed successfully.
```

It would be nice if this bug was fixed.

**Comment by hickeyma** [comment] 2021-06-02 14:33
@ramalhais-sky Thank you for finding this. Have verified that this is a bug for Helm v2 only. It is working for Helm v3.
Do you feel like pushing a PR for this?

**Comment by MrLuje** [comment] 2021-06-13 17:00
AFAIK, kube-context flag is not forwarded to plugins in helm v2 and this is by design (cf [plugins.md](https://github.com/helm/helm/blob/release-2.14/docs/plugins.md#a-note-on-flag-parsing) & [this helm issue](https://github.com/helm/helm/issues/4744))
```
--kube-context: This is simply dropped. If your plugin uses useTunnel, this is used to set up the tunnel for you.
```
A few thoughts to help on this :
- maybe using a custom flag instead of kube-context (but it may weird to have a different flag between helm2 and 3...)
- printing the current context during the process so this behavior won't be "hidden"

The good news is that this limitation was dropped in helm 3, hence if you run this plugin with helm3 you won't have this issue (and helm3 can be used to migrate helm2 releases 🙂 without any issue)

**Comment by hickeyma** [comment] 2021-06-15 08:49
@MrLuje Thank you for the "heads up". I hadn't realized the flag was dropped for Helm 2 plugins. Thinking about it now, `mapkubeapis` was initially developed and tested using Helm 3 primarily because it was the latest supported release and Helm 2 was due for EOL.  This could be why this issue did not become apparent till now.

As [Helm 2 is now unsupported](https://helm.sh/blog/helm-2-becomes-unsupported/) and the issue is in Helm 2 core then it is not possible to fix this. Adding a custom flag which is a workaround/hack for Helm 2 is not something we are going to do considering it is specifically for Helm 2 and especially that it is now EOL.

@ramalhais-sky You can use Helm 3 (current supported release) instead to install the plugin and the `--v2` flag to map any Helm 2 releases.

Let me know if that will work for you.

**Comment by hickeyma** [comment] 2021-08-31 10:30
Closing as won't fix and reason for not fixing accepted by the OP.

**Closed by hickeyma** 2021-08-31 10:30 UTC
Labels: bug, wontfix
